### ISSUE TITLE
If a subscribe callback subscribes to the same event, ConcurrentModificationException is thrown

### ISSUE THREAD

**Issue by etanhatch** [Rasalexman/KDispatcher#4]
Since the list of callbacks is being iterated during the subscribe() callback, a new subscribe inside the call hierarchy of the callback calls add() to the same list. Therefore a ConcurrentModificationException is thrown.

**Comment by Rasalexman** [comment]
@etanhatch thanks for adding this issue. I will fix it in next releases

**Comment by Rasalexman** [comment]
@etanhatch i fixed this issue in release version 1.1.6
